DariBerrie/loopyex

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20221029104923_devise_create_users.rb
db/migrate/20221029105513_add_names_and_address_to_users.rb
db/schema.rb
test/models/user_test.rb

Please accept, my first one :D

feat: added user model and device gem

---

app/models/user.rb
app/models/yarn.rb
db/migrate/20221029121423_create_yarns.rb
db/schema.rb
test/models/yarn_test.rb

Please check if my yarn model is correct.

Added yarn model

---

Gemfile.lock
db/migrate/20221029131352_add_columns_to_yarn.rb
db/schema.rb

I added new fields to our yarn table!

Add columns to yarn

---

app/controllers/orders_controller.rb
app/controllers/yarns_controller.rb
app/views/yarns/index.html.erb
config/routes.rb
test/controllers/orders_controller_test.rb
test/controllers/yarns_controller_test.rb

Let me know what you guys think of the controllers, routes and view.

feat: created yarns, orders controllers and yarn#index view

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
app/views/yarns/index.html.erb
db/seeds.rb

feat: database seeded, faker gem installed

---

app/assets/stylesheets/pages/_home.scss
app/controllers/products_controller.rb
app/models/product.rb
config/environments/development.rb
config/storage.yml
db/migrate/20221101172655_create_active_storage_tables.active_storage.rb
db/schema.rb

Added Active Storage! Make sure to add the Cloudinary API key to your .env file and migrate :)

feat: added Active Storage

---

config/routes.rb

added routes for products controller actions

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/yarns/index.html.erb

Responsiveness added to landing page, background image fixed to cover all width and height.

feat: Landing page design and responsiveness

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/views/pages/home.html.erb
app/views/products/index.html.erb
app/views/shared/_card.html.erb

Changed the size of the cards, made price slightly more visible, fixed the home page, it includes the background picture now as well as navbar.

feat: card and home design

---

app/models/product.rb

Added some inclusion validations for :brand and :weight in our product model. This should help make our forms more elegant.

Inclusion for products brand weight

---

app/controllers/yarns_controller.rb
app/views/yarns/index.html.erb
db/migrate/20221103190846_drop_orders.rb
db/migrate/20221103191108_drop_yarns.rb
db/schema.rb

Reverts DariBerrie/loopyex#31
Needs more work

Revert "fix: trying to fix DB by removing yarns from schema"

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/products_controller.rb
app/views/products/new.html.erb

- Imported the form to the application.scss
- removed the background image
- added a dropdown list to the form with the valid data options 
- the submit button works and redirects to the product's page

added dropdown list to the form and fixed the submit

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/products_controller.rb
app/controllers/yarns_controller.rb
app/views/pages/home.html.erb
app/views/products/index.html.erb
app/views/shared/_card.html.erb
app/views/shared/_navbar.html.erb

added one search field on the main page, managed to make all the cards link to correct products (thanks for your help guys)

feat: all cards as a link, one search field added

---

app/controllers/orders_controller.rb
config/routes.rb

Created routes and controller for order model.

created routes and controller for orders

---

app/assets/stylesheets/components/_navbar.scss
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Updates:
- Added favicon to tab
- Buried all User functionality links in the drop down
- Aligned Welcome User message to right
- Fixed Devise Button to match Product form button
- Added Dari's user image

Updated navbar styling & functionality. Again. :)

---

Gemfile
Gemfile.lock
app/models/product.rb
app/views/layouts/application.html.erb
app/views/products/new.html.erb
config/initializers/geocoder.rb
db/migrate/20221105102053_add_coordinates_to_users.rb
db/migrate/20221105103247_remove_coordinates_from_users.rb
db/migrate/20221105103348_add_coordinates_to_products.rb
db/migrate/20221105112937_add_address_to_products.rb
db/schema.rb

Added the geocode gem and changed the products model. 
We don't need to merge this to the master 😄

add geocode to products

---

app/controllers/orders_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/views/layouts/application.html.erb
app/views/products/index.html.erb

Added map controller, added markers to the map, inserted map on products page, can't see anything yet as it needs the data

feat: added map frontend, maps controller

---

app/controllers/products_controller.rb
app/javascript/application.js
app/views/products/index.html.erb
db/schema.rb
db/seeds.rb

added markers to the map, seeded db with 4 addresses

feat: added markers to the map

---

app/assets/stylesheets/components/_card.scss
db/schema.rb

Updated the max image height of a card.

Card update

---

app/models/product.rb
app/views/orders/new.html.erb
app/views/products/show.html.erb
db/schema.rb

fix: updated product model, products#show view and orders#new view

fix: updated product model, products#show view and orders#new view

---

app/views/shared/_card.html.erb

Dollah dollah bills to euro! €

Changed currency on Index product page

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/models/product.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/products/show.html.erb
app/views/shared/_card.html.erb
db/migrate/20221107174841_add_description_to_products.rb
db/migrate/20221107175009_change_price_to_integer_in_products.rb
db/schema.rb
db/seeds.rb

Revert "Product model"

---

app/assets/stylesheets/components/_footer.scss
app/views/orders/new.html.erb
app/views/products/show.html.erb

fix: updated page to provide more info on order and added a confirmation message window before purchase

Order new html

---

app/models/user.rb
db/schema.rb
db/seeds.rb

added photo to user model

---

app/assets/stylesheets/components/_avatar.scss
app/models/product.rb
app/views/products/show.html.erb
db/migrate/20221108184320_add_description_to_products.rb
db/migrate/20221108184352_change_price_to_integer_in_products.rb
db/seeds.rb

Another fix to get back code lost

fix:getting product model changes back

---

app/assets/stylesheets/components/_card.scss
app/views/products/index.html.erb
app/views/products/new.html.erb
app/views/shared/_card.html.erb

border radius added on the cards and map, cards are displayed by created_at order, date changed to days ago. Date still needs work as it always shows 'days' need to be conditional ie 0 = today, 1 = day ago, >1 = days ago

feat: sorting of the cards added

---

app/controllers/products_controller.rb
app/models/product.rb

Updated model and strong params to include address and description

updated product model and controller

---

app/controllers/orders_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/orders/index.html.erb
app/views/products/show.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

Updates:
- Created a Users Controller
- Added a User Orders page (WIP!)
- Added a User Products page "My Stash" (for any user, including current)
Still working on:
- Design
- Linking & viewing orders
- Adding user profile image and info to the top of the User Products page

User products and orders page updates

---

db/migrate/20221109082924_remove_description_from_products.rb
db/migrate/20221109083230_add_description_to_products.rb
db/schema.rb

Locally our masters are fine, but it is creating some weirdness when pushed to Heroku since "description" was not initially added (according to our masters). Trying to fix that.

fix: fixing description weirdness in DB

---

app/assets/stylesheets/components/_form.scss
app/views/products/new.html.erb

Hi all, 
I made some changes to the new product form. I tried to make the labels inline with the input fields, but i couldn't find a way to do that with non-boolean values. So in the end I just added some paddings and changed the size of the container

Update new product form

---

app/assets/stylesheets/application.scss

Rounded the edges of the edit profile card

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/index.js
app/javascript/controllers/navbar_controller.js
app/views/shared/_navbar.html.erb

app name added to navbar, border added to navbar and footer, working on making navbar sticky

Navbar updates

---

app/views/orders/new.html.erb

Added price on the order page.

fix: Added price to order#new view

---

Gemfile.lock
app/assets/stylesheets/components/_form.scss
app/views/products/new.html.erb

Price and quantity in the same line

---

app/views/shared/_navbar.html.erb

Just adjusted the navbar to change to current_user photo instead of my photo.

fix: added current_user avatar to navbar

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/products_controller.rb
app/javascript/controllers/map_controller.js
app/javascript/controllers/show_map_controller.js
app/views/products/_info_window.html.erb

changed the marker icon to our logo, on the pop-up i left the product name, description, and button to product page. I tried to put user avatar there, but to be honest I gave up after 1 hour... :P

Info window

---

app/assets/stylesheets/config/_colors.scss
app/views/devise/registrations/edit.html.erb
app/views/pages/home.html.erb

made homepage button rounder (more pill-like), increased font size and weight, and adjusted the green & orange colors to be a bit more pastel across the site (let me know if the colors aren't as pleasing now).

fix to homepage button

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb

updated devise strong params in application_controller to allow one photo when the user edits their avatar

fix: user account edit journey is complete!

---

app/assets/stylesheets/components/_avatar.scss

Made avatar a fixed square in the navbar.

fix: made navbar avatar square

---

app/assets/stylesheets/config/_colors.scss

fix: made red a softer pink

---

app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/orders/index.html.erb
app/views/orders/new.html.erb
app/views/products/show.html.erb

Added bottom margin and padding to containers to prevent the page from being hidden by footer.

fix: added bottom margin and padding

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/config/_fonts.scss
app/javascript/controllers/show_map_controller.js
app/views/layouts/application.html.erb
app/views/products/_info_window.html.erb
app/views/shared/_navbar.html.erb

removed the 'x' from the pop-up window, added subtle box shadow transformation to cards, made a 'loopyex' a link to products page,

fix: added box shadow to cards and few other bits

---

app/assets/stylesheets/components/_form.scss
app/models/product.rb
app/views/products/edit.html.erb
app/views/products/new.html.erb

Added the green button and a dropdown list for the material

changed the new product form's style

---

app/assets/stylesheets/components/_alert.scss
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

fixed the alert/notice pop-up, can still adjust the location of it, currently is in top-right corner as per picture attached.

fixed alert and notice

---

app/assets/stylesheets/pages/_index.scss
app/controllers/products_controller.rb
app/models/product.rb
app/views/products/index.html.erb

Search function now searches through product's name, brand, weight, color, description, material
Search bar looks pretty now

changed search function and the style of the search bar

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss
app/views/products/index.html.erb
app/views/shared/_card.html.erb

something looks weird. I must have inserted a typo

Revert "fix: added avatars to index cards"

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss
app/views/shared/_card.html.erb

Index cards

---

app/views/products/show.html.erb

adjusted map height to match carousel height.

fix: adjust map height

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

centered logo text on page and adjusted slogan

fix: centered logo text on page and adjusted slogan

---

app/views/products/edit.html.erb

fixed delete method in edit.html.erb

fix: delete method

---

app/controllers/application_controller.rb
app/helpers/meta_tags_helper.rb
app/views/layouts/application.html.erb
config/initializers/default_meta.rb
config/meta.yml

Added all the meta tags and facebook OG:Pic to show properly

feat: added all necessary meta tags
